name: Daka

on:
  schedule:
    - cron: '30 1 * * *'
    - cron: '0 11 * * *'

jobs:
  daka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Let's Daka
        run: node daka.js
        env:
          FEMAS_USERNAME: ${{ secrets.FEMAS_USERNAME }}
          FEMAS_PASSWORD: ${{ secrets.FEMAS_PASSWORD }}
          DELAY_MIN_MINUTE: ${{ secrets.DELAY_MIN_MINUTE }}
          DELAY_MAX_MINUTE: ${{ secrets.DELAY_MAX_MINUTE }}
